---
- project:
    check:
      jobs:
        - maven-build:
            nodeset:
              nodes:
                - name: builder
                  label: cloud-centos-8-stream
    gate:
      jobs:
        - maven-build:
            nodeset:
              nodes:
                - name: builder
                  label: cloud-centos-8-stream